on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted # Используем self-hosted runner

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Сборка Docker образа
      - name: Build Docker image
        run: |
          make build

      # Шаг 3: Запуск контейнера в docker compose
      - name: Stop and remove existing container
        run: |
          whoami
          cd /home/alim/projects/tg-market
          docker compose up -d --force-recreate tg-market-front
